# CI/CD

image: archlinux
packages:
  - rustup
  - shaderc # required for feature "spirv"
sources:
  - https://git.sr.ht/~hadronized/glsl
tasks:
  # glsl + glsl-tree
  - setup: |
      rustup set profile minimal
      rustup default stable
      rustup component add rustfmt clippy
  - build: |
      cd glsl
      cargo build --features spirv
  - test: |
      cd glsl
      cargo test --features spirv
  - build-minimal: |
      rustup default nightly
      cd glsl
      cargo build -Z minimal-versions --features spirv
  - test-minimal: |
      rustup default nightly
      cd glsl
      cargo test -Z minimal-versions -- all-features

  # glsl-quasiquote
  - glsl-quasiquote-setup: |
      rustup default nightly
      rustup component add rustfmt clippy
  - glsl-quasiquote-build: |
      cd glsl
      cargo build --features spirv
  - glsl-quasiquote-test: |
      cd glsl
      cargo test --features spirv
  - glsl-quasiquote-build-minimal: |
      cd glsl
      cargo build -Z minimal-versions --features spirv
  - glsl-quasiquote-test-minimal: |
      cd glsl
      cargo test -Z minimal-versions --features spirv
